
name: Greetings on variable day

on:
  workflow_dispatch:


jobs:
  greeting_job:
    runs-on: ubuntu-latest


    steps:
      - name: set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"

      - name: use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'
